require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('Error: Make sure NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are set in your .env file.');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

const USER_EMAIL = 'vahid.askari1986@gmail.com';
const ROLE_TO_ASSIGN = 'admin';

const assignAdminRole = async () => {
  console.log(`Attempting to assign '${ROLE_TO_ASSIGN}' role to user with email: ${USER_EMAIL}`);

  try {
    // Note: listUsers is deprecated. Using it for simplicity as per user's context.
    // A better approach would be to get user by email if the API supports it directly.
    const { data: { users }, error: listError } = await supabase.auth.admin.listUsers();

    if (listError) {
      throw listError;
    }

    const user = users.find(u => u.email === USER_EMAIL);

    if (!user) {
      console.error(`Error: User with email '${USER_EMAIL}' not found.`);
      return;
    }

    const userId = user.id;
    console.log(`Found user with ID: ${userId}`);

    const { data: existingRole, error: selectError } = await supabase
      .from('user_roles')
      .select('*')
      .eq('user_id', userId)
      .eq('role', ROLE_TO_ASSIGN)
      .maybeSingle();

    if (selectError && selectError.code !== 'PGRST116') { // PGRST116 means no rows found, which is fine
        // However, if it's a different error, we should throw it.
        if (selectError.message.includes('relation "public.user_roles" does not exist')) {
             console.log('The `user_roles` table does not exist. I will provide the SQL to create it.');
             const createTableSql = `
CREATE TABLE public.user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, role)
);

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Policies for user_roles
CREATE POLICY "Allow admins to view all user roles" ON public.user_roles FOR SELECT TO authenticated USING ((get_my_claim(\'user_role\') = '"admin"'::jsonb));
CREATE POLICY "Allow users to view their own roles" ON public.user_roles FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Allow admins to insert roles" ON public.user_roles FOR INSERT TO authenticated WITH CHECK ((get_my_claim(\'user_role\') = '"admin"'::jsonb));
CREATE POLICY "Allow admins to delete roles" ON public.user_roles FOR DELETE TO authenticated USING ((get_my_claim(\'user_role\') = '"admin"'::jsonb));
        `;
        console.log('--- SQL to create user_roles table ---');
        console.log(createTableSql);
        console.log('--------------------------------------');
        console.log('Please run this SQL in your Supabase SQL Editor and then run this script again.');
        return;
        }
       throw selectError;
    }

    if (existingRole) {
      console.log(`User '${USER_EMAIL}' already has the '${ROLE_TO_ASSIGN}' role.`);
      return;
    }

    console.log(`User does not have the '${ROLE_TO_ASSIGN}' role. Proceeding to assign...`);

    const { error: insertError } = await supabase
      .from('user_roles')
      .insert({ user_id: userId, role: ROLE_TO_ASSIGN });

    if (insertError) {
        throw insertError;
    }

    console.log('--- ✅ Success! ---');
    console.log(`Successfully assigned the '${ROLE_TO_ASSIGN}' role to user '${USER_EMAIL}'.`);

  } catch (error) {
    console.error('\n--- ❌ An error occurred ---');
    if (error.code) console.error(`Error Code: ${error.code}`);
    if (error.message) console.error(`Error Message: ${error.message}`);
    console.error('---------------------------\n');
  }
};

assignAdminRole();