/*
-- =============================================
-- Author: Gemini
-- Create date: 2024-07-30
-- Description: FINAL FIX. This script sets up the 'home_page' table EXACTLY as the frontend code expects.
-- It deletes the old table and creates a new one with the correct JSON structure for "Arman Hamrah".
-- =============================================
*/

-- Step 1: Drop the old table to remove any lingering incorrect data.
DROP TABLE IF EXISTS public.home_page;

-- Step 2: Create the table 'home_page' with the schema the code requires (a JSONB column for content).
CREATE TABLE public.home_page (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  section TEXT UNIQUE NOT NULL, -- 'hero', 'brands', etc.
  content JSONB -- The content for the section in JSON format
);

-- Step 3: Enable Row Level Security and create a policy for public read access.
ALTER TABLE public.home_page ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access for home_page"
ON public.home_page
FOR SELECT
USING (true);

-- Step 4: Insert the CORRECT data for "Arman Hamrah" in the CORRECT JSON format.

-- Insert Hero Section Data
INSERT INTO public.home_page (section, content)
VALUES
('hero', '{ 
  "title": { "fa": "آرمان همراه ارتباطات آریا", "en": "Arman Hamrah Ertebatat Aria" },
  "subtitle": { "fa": "آینده دیجیتال خود را با ما بسازید", "en": "Build Your Digital Future with Us" },
  "cta_text": { "fa": "مشاهده محصولات", "en": "View Products" },
  "cta_link": "/products",
  "image_url": "/assets/hero-bg.jpg"
}');

-- Insert Brands Section Data
INSERT INTO public.home_page (section, content)
VALUES
('brands', '[ 
  { "id": 1, "name": "Arman Fire", "logo_url": "/assets/arman-fire-logo.jpg" },
  { "id": 2, "name": "Radical", "logo_url": "/assets/radical-logo.jpeg" },
  { "id": 3, "name": "Arman Aria", "logo_url": "/assets/arman-aria-logo.png" }
]');
