/*
-- =============================================
-- Author: Gemini
-- Create date: 2024-07-30
-- Description: THE DEFINITIVE SEED SCRIPT for 'Arman Hamrah'.
-- This script correctly sets up the entire database from scratch.
-- It creates and populates BOTH 'home_page' and 'page_content' tables.
-- PLEASE RUN THIS SCRIPT IN YOUR SUPABASE SQL EDITOR.
-- =============================================
*/

-- Step 1: Drop old tables to ensure a completely clean start.
DROP TABLE IF EXISTS public.home_page CASCADE;
DROP TABLE IF EXISTS public.page_content CASCADE;

-- Step 2: Create the 'home_page' table for the dynamic homepage sections.
CREATE TABLE public.home_page (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  section TEXT UNIQUE NOT NULL, -- e.g., 'hero', 'brands'
  content JSONB -- The content for the section in JSON format
);
ALTER TABLE public.home_page ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can read homepage sections" ON public.home_page FOR SELECT USING (true);

-- Step 3: Create the 'page_content' table for global UI text and translations.
CREATE TABLE public.page_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  page TEXT NOT NULL,          -- e.g., 'global', 'contact'
  section TEXT NOT NULL,       -- e.g., 'navigation', 'footer'
  element_key TEXT NOT NULL,   -- The translation key (e.g., 'nav.home')
  fa_text TEXT,                -- Text in Farsi
  en_text TEXT,                -- Text in English
  UNIQUE(page, section, element_key)
);
ALTER TABLE public.page_content ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can read page content" ON public.page_content FOR SELECT USING (true);

-- =============================================
-- SEED ALL DATA FOR "ARMAN HAMRAH"
-- =============================================

-- Step 4: Insert content for the 'home_page' table.
INSERT INTO public.home_page (section, content)
VALUES
('hero', '{ 
  "title": { "fa": "آرمان همراه ارتباطات آریا", "en": "Arman Hamrah Ertebatat Aria" },
  "subtitle": { "fa": "آینده دیجیتال خود را با ما بسازید", "en": "Build Your Digital Future with Us" },
  "cta_text": { "fa": "مشاهده محصولات", "en": "View Products" },
  "cta_link": "/products",
  "image_url": "/assets/hero-bg.jpg"
}'),
('brands', '[ 
  { "id": 1, "name": "Arman Fire", "logo_url": "/assets/arman-fire-logo.jpg" },
  { "id": 2, "name": "Radical", "logo_url": "/assets/radical-logo.jpeg" },
  { "id": 3, "name": "Arman Aria", "logo_url": "/assets/arman-aria-logo.png" }
]');

-- Step 5: Insert all UI text translations for the 'page_content' table.
INSERT INTO public.page_content (page, section, element_key, fa_text, en_text)
VALUES
  -- Navigation Bar
  ('global', 'navigation', 'nav.home', 'خانه', 'Home'),
  ('global', 'navigation', 'nav.warranty', 'گارانتی', 'Warranty'),
  ('global', 'navigation', 'nav.products', 'محصولات', 'Products'),
  ('global', 'navigation', 'nav.export', 'صادرات', 'Export'),
  ('global', 'navigation', 'nav.representatives', 'نمایندگان', 'Representatives'),
  ('global', 'navigation', 'nav.contact', 'تماس با ما', 'Contact Us'),
  ('global', 'navigation', 'nav.profile', 'پروفایل', 'Profile'),
  ('global', 'navigation', 'nav.logout', 'خروج', 'Sign Out'),
  ('global', 'navigation', 'nav.myArman', 'آرمان من', 'My Arman'),

  -- Footer
  ('global', 'footer', 'footer_description', 'آرمان همراه، پیشرو در ارائه جدیدترین محصولات و خدمات دیجیتال.', 'Arman Hamrah, a leader in providing the latest digital products and services.'),
  ('global', 'footer', 'footer_copyright', '© ۱۴۰۳ کلیه حقوق این وب‌سایت متعلق به شرکت آرمان همراه ارتباطات آریا می‌باشد.', '© 2024 All rights reserved for Arman Hamrah Ertebatat Aria.');
