import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'fa' | 'en';
type Direction = 'rtl' | 'ltr';

interface LanguageContextType {
  language: Language;
  direction: Direction;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  fa: {
    // General
    'all': 'همه',
    'product.coming_soon': 'اطلاعات این محصول به زودی تکمیل می‌شود.',

    // Brands
    'Apple': 'اپل',
    'Samsung': 'سامسونگ',
    'Xiaomi': 'شیائومی',
    'Poco': 'پوکو',
    'Nokia': 'نوکیا',

    // Categories
    'category.mobile': 'موبایل',
    'category.smartwatch': 'ساعت هوشمند',
    'category.tablet': 'تبلت',
    'category.accessories': 'لوازم جانبی',
    'category.feature_phone': 'موبایل ساده',

    // Navigation
    'nav.home': 'صفحه اصلی',
    'nav.warranty': 'گارانتی آرمان همراه',
    'nav.products': 'محصولات',
    'nav.export': 'صادرات',
    'nav.representatives': 'نمایندگان',
    'nav.blog': 'بلاگ و آموزش',
    'nav.contact': 'تماس با ما',
    'nav.myArman': 'ثبت نام',
    'nav.cooperation': 'همکاری با ما',
    
    // Hero
    'hero.title': 'هوشمندترین گارانتی و خدمات',
    'hero.subtitle': 'پس از فروش در ایران',
    'hero.description': 'شرکت گارانتی آرمان همراه ارتباطات آریا از سال ۱۳۹۳ تا کنون با بهترین تجربه در ارائه خدمات به مشتریان',
    'hero.cta': 'خدمات ما',
    'hero.cta2': 'ثبت نام',
    
    // Brands
    'brands.title': 'برندهای تحت پوشش',
    
    // Services
    'services.title': 'خدمات ما',
    'services.warranty.title': 'گارانتی آرمان همراه',
    'services.warranty.desc': 'گارانتی معتبر برای محصولات اپل، سامسونگ، شیائومی و سونی',
    'services.representatives.title': 'نمایندگان',
    'services.representatives.desc': 'شبکه گسترده نمایندگان آرمان همراه در سراسر ایران',
    'services.shop.title': 'فروشگاه',
    'services.shop.desc': 'خرید محصولات اصل با گارانتی معتبر',
    'services.export.title': 'صادرات',
    'services.export.desc': 'صادرات محصولات به سراسر جهان',

    // Subsidiaries
    'subsidiaries.title': 'شرکت‌های زیرمجموعه',
    'subsidiary.1.name': 'آیین تجارت آران',
    'subsidiary.2.name': 'آرشا فن آوران رادان',
    'subsidiary.3.name': 'آرتا تجارت کیهان',
    'subsidiary.4.name': 'فرنام تجارت دادار',
    'subsidiary.5.name': 'دانیال تجارت دارا',
    'subsidiary.6.name': 'فرنام تجارت کارا',
    'subsidiary.7.name': 'کارزین تجارت آرشان',
    'subsidiary.8.name': 'مانیا تجارت ماکان',
    'subsidiary.9.name': 'کارزین تجارت آرشان',
    'subsidiary.10.name': 'رادیکال وان',

    // Products Page
    'products.title': 'محصولات',
    'products.back': 'بازگشت به صفحه اصلی',
    'products.back_to_list': 'بازگشت به لیست محصولات',
    'products.description': 'تمامی محصولات با گارانتی معتبر آرمان همراه ارتباطات آریا عرضه می‌شوند',
    'products.brand': 'برند:',
    'products.category': 'دسته‌بندی:',
    'products.view': 'مشاهده',
    'products.noProducts': 'محصولی یافت نشد',
    'products.not_found': 'محصول یافت نشد',
    'products.intro': 'معرفی محصول',
    'products.specs': 'مشخصات فنی',
    'products.specs_soon': 'مشخصات فنی این محصول به زودی اضافه خواهد شد.',
    'products.seo.title': 'محصولات | آرمان همراه ارتباطات آریا',
    'products.seo.description': 'مشاهده تمامی محصولات اپل، سامسونگ با گارانتی آرمان همراه - آیفون، گلکسی، اپل واچ و ساعت‌های هوشمند',

    // Export Page
    'export.back': 'بازگشت به صفحه صادرات',
    'export.title_main': 'صادرات آرمان',
    'export.subtitle_main': 'بهترین راهکار برای واردات کالا از ایران',
    'export.description_main': 'با بیش از ۹ سال تجربه، شرکت آرمان در واردات و صادرات کالاهای اساسی و تخصصی در بخش‌های مختلف از جمله فناوری اطلاعات، مواد غذایی، پوشاک، نفت، فلزات و مصالح ساختمانی فعالیت موفقی داشته است.',
    'export.features.title': 'ویژگی‌های خدمات صادراتی',
    'export.features.international.title': 'صادرات بین‌المللی',
    'export.features.international.description': 'صادرات محصولات به کشورهای منطقه خلیج فارس، آسیای میانه و کشورهای همسایه',
    'export.features.transportation.title': 'حمل و نقل امن',
    'export.features.transportation.description': 'ارسال ایمن کالا با بیمه کامل و ردیابی آنلاین محموله در تمام مراحل',
    'export.features.original.title': 'محصولات اورجینال',
    'export.features.original.description': 'تضمین اصالت کالا با گارانتی معتبر بین‌المللی و سرتیفیکیت اصالت',
    'export.features.documentation.title': 'مستندات کامل',
    'export.features.documentation.description': 'تهیه کلیه مدارک گمرکی، اسناد صادراتی و مجوزهای لازم',
    'export.products.title': 'محصولات صادراتی',
    'export.products.view_details': 'مشاهده جزئیات',
    'export.products.category.metals': 'فلزات',
    'export.products.category.petrochemical': 'پتروشیمی',
    'export.products.category.textile': 'نساجی',
    'export.products.iron_steel.name': 'آهن و فولاد',
    'export.products.iron_steel.description': 'بهترین و با کیفیت‌ترین آهن و فولاد در بازار ایران',
    'export.products.copper_rod.name': 'مفتول مسی',
    'export.products.copper_rod.description': 'بهترین و با کیفیت‌ترین مفتول مسی در بازار ایران',
    'export.products.bitumen.name': 'قیر',
    'export.products.bitumen.description': 'بهترین و با کیفیت‌ترین قیر در بازار ایران',
    'export.products.oil.name': 'روغن',
    'export.products.oil.description': 'بهترین و با کیفیت‌ترین روغن‌های صنعتی و پایه در بازار ایران',
    'export.products.thread.name': 'نخ',
    'export.products.thread.description': 'بهترین و با کیفیت‌ترین نخ در بازار ایران',
    'export.services.title': 'خدمات صادراتی ما',
    'export.services.packaging.title': 'بسته‌بندی صادراتی',
    'export.services.packaging.description': 'بسته‌بندی استاندارد و حرفه‌ای مطابق با استانداردهای بین‌المللی',
    'export.services.clearance.title': 'ترخیص گمرکی',
    'export.services.clearance.description': 'انجام کلیه امور گمرکی و ترخیص کالا در مبدا و مقصد',
    'export.services.quality.title': 'تضمین کیفیت',
    'export.services.quality.description': 'بازرسی و کنترل کیفیت تمامی محصولات قبل از ارسال',
    'export.goal.title': 'هدف ما',
    'export.goal.description': 'با بیش از ۹ سال تجربه، شرکت آرمان با موفقیت در واردات و صادرات کالاهای اساسی و تخصصی در بخش‌های مختلف از جمله فناوری اطلاعات، مواد غذایی، پوشاک، نفت، فلزات و مصالح ساختمانی فعالیت داشته است. هدف شرکت ایجاد ارتباطات تجاری گسترده در سراسر جهان است.',
    'export.countries.title': 'کشورهای هدف صادرات',
    'export.countries.subtitle': 'صادرات به کشورهای منطقه و همسایه',
    'country.uae': 'امارات',
    'country.iraq': 'عراق',
    'country.afghanistan': 'افغانستان',
    'country.turkmenistan': 'ترکمنستان',
    'country.azerbaijan': 'آذربایجان',
    'country.armenia': 'ارمنستان',
    'country.qatar': 'قطر',
    'country.kuwait': 'کویت',
    'export.contact.title': 'تماس با ما',
    'export.contact.subtitle': 'برای اطلاعات بیشتر با متخصصین ما تماس بگیرید',
    'export.contact.phone': 'تلفن',
    'export.contact.address': 'آدرس',
    'export.contact.address_value': 'واحد ۳۰۴، طبقه ۳، ساختمان امیر اتابک، خیابان سلیمان خاطر، خیابان مطهری، تهران',
    'export.form.title': 'فرم تماس',
    'export.form.full_name': 'نام کامل',
    'export.form.full_name_placeholder': 'نام کامل شما',
    'export.form.company_name': 'نام شرکت',
    'export.form.company_name_placeholder': 'نام شرکت شما',
    'export.form.message': 'پیام شما',
    'export.form.message_placeholder': 'چطور می‌توانیم به شما کمک کنیم؟',
    'export.form.send': 'ارسال پیام',
    'export.cta.title': 'کسب و کار خود را با ما شروع کنید',
    'export.cta.subtitle': 'کارشناسان تجاری ما همواره در تلاش هستند تا راحتی کسب و کار شما را افزایش دهند.',
    'export.cta.button_start': 'شروع مکالمه',
    'export.seo.title': 'صادرات | بهترین راهکار برای واردات کالا از ایران',
    'export.seo.description': 'خدمات صادرات محصولات به کشورهای منطقه - آهن و فولاد، مفتول مسی، قیر، روغن و نخ',
    
    // Bitumen Page
    'bitumen.title': 'قیر',
    'bitumen.subtitle': 'Bitumen',
    'bitumen.category': 'پتروشیمی',
    'bitumen.description': 'بهترین و با کیفیت‌ترین قیر در بازار ایران، تولید شده در پالایشگاه‌های معتبر و مطابق با استانداردهای بین‌المللی.',
    'bitumen.gradesTitle': 'گریدهای موجود',
    'bitumen.specsTitle': 'مشخصات فنی محصول',
    'bitumen.feature1.title': 'تولید پالایشگاهی',
    'bitumen.feature1.desc': 'تولید شده در پالایشگاه‌های معتبر ایران',
    'bitumen.feature2.title': 'کیفیت تضمینی',
    'bitumen.feature2.desc': 'تضمین کیفیت با استانداردهای بین‌المللی',
    'bitumen.feature3.title': 'گواهینامه‌ها',
    'bitumen.feature3.desc': 'مطابق با استانداردهای ASTM',
    'bitumen.feature4.title': 'مستندات کامل',
    'bitumen.feature4.desc': 'ارائه تمامی مدارک و سرتیفیکیت‌ها',
    'bitumen.table.characteristic': 'ویژگی',
    'bitumen.table.unit': 'واحد',
    'bitumen.table.specification': 'مشخصات',
    'bitumen.table.testMethod': 'روش تست',
    'bitumen.spec.penetration': 'درجه نفوذ @25°C',
    'bitumen.spec.specificGravity': 'وزن مخصوص @25°C',
    'bitumen.spec.softeningPoint': 'نقطه نرمی',
    'bitumen.spec.ductility': 'خاصیت انگمی @25°C',
    'bitumen.spec.lossOnHeating': 'افت وزنی در اثر حرارت',
    'bitumen.spec.dropInPenetration': 'کاهش درجه نفوذ پس از افت وزنی',
    'bitumen.spec.flashPoint': 'نقطه اشتعال',
    'bitumen.spec.solubility': 'درجه حلالیت در CS2',
    'bitumen.seo.title': 'صادرات قیر | آرمان همراه',
    'bitumen.seo.description': 'صادرات بهترین و با کیفیت‌ترین قیر ایران در گریدهای مختلف (60/70, VG10, VG30) با تضمین کیفیت و استانداردهای بین‌المللی.',

    // Copper Rod Page
    'copper.title': 'مفتول مسی',
    'copper.subtitle': 'Copper Rod',
    'copper.description': 'صادرات مفتول مس با کیفیت بالا و خلوص ۹۹.۹٪، تولید شده مطابق با استانداردهای جهانی برای صنایع کابل و سیم.',
    'copper.featuresTitle': 'ویژگی‌های مفتول مس',
    'copper.feature1.title': 'انعطاف‌پذیری بالا',
    'copper.feature1.desc': 'مناسب برای انواع کاربردهای صنعتی و ساختمانی',
    'copper.feature2.title': 'هدایت الکتریکی عالی',
    'copper.feature2.desc': 'تضمین کمترین اتلاف انرژی در انتقال برق',
    'copper.feature3.title': 'استاندارد جهانی',
    'copper.feature3.desc': 'تولید مطابق با استاندارد ASTM B49',
    'copper.feature4.title': 'بسته‌بندی مطمئن',
    'copper.feature4.desc': 'حفاظت کامل محصول در برابر اکسیداسیون و آسیب',
    'copper.specsTitle': 'مشخصات فنی مفتول مس',
    'copper.table.characteristic': 'مشخصه',
    'copper.table.value': 'مقدار',
    'copper.spec.diameter': 'قطر',
    'copper.spec.conductivity': 'هدایت الکتریکی',
    'copper.spec.tensile': 'مقاومت کششی',
    'copper.spec.elongation': 'ازدیاد طول',
    'copper.spec.purity': 'درجه خلوص',
    'copper.spec.standard': 'استاندارد',
    'copper.seo.title': 'صادرات مفتول مسی | آرمان همراه',
    'copper.seo.description': 'صادرات مفتول مسی با خلوص ۹۹.۹٪ و هدایت الکتریکی بالا، مطابق با استاندارد ASTM B49 برای صنایع کابل.',

    // Iron & Steel Page
    'iron.title': 'آهن و فولاد',
    'iron.subtitle': 'Iron & Steel',
    'iron.description': 'تأمین و صادرات انواع محصولات فولادی از جمله میلگرد، ورق، شمش و پروفیل‌های ساختمانی با بهترین کیفیت از کارخانه‌های معتبر ایران.',
    'iron.productsTitle': 'محصولات قابل تأمین',
    'iron.product1.name': 'میلگرد (Rebar)',
    'iron.product1.desc': 'انواع میلگرد آجدار و ساده در سایزهای مختلف',
    'iron.product2.name': 'ورق فولادی (Steel Sheet)',
    'iron.product2.desc': 'ورق گرم، ورق سرد، ورق گالوانیزه و رنگی',
    'iron.product3.name': 'شمش (Billet/Bloom/Slab)',
    'iron.product3.desc': 'انواع شمش فولادی برای کاربردهای نورد',
    'iron.product4.name': 'تیرآهن (Beam)',
    'iron.product4.desc': 'تیرآهن IPE, IPB و هاش در سایزهای استاندارد',
    'iron.product5.name': 'پروفیل (Profile)',
    'iron.product5.desc': 'انواع قوطی و پروفیل‌های ساختمانی و صنعتی',
    'iron.product6.name': 'نبشی و ناودانی (Angle/Channel)',
    'iron.product6.desc': 'نبشی و ناودانی فولادی در ابعاد متنوع',
    'iron.featuresTitle': 'چرا آهن و فولاد ایران؟',
    'iron.feature1.title': 'تولیدکنندگان برتر',
    'iron.feature1.desc': 'تأمین از بزرگترین و معتبرترین کارخانجات فولاد ایران',
    'iron.feature2.title': 'کنترل کیفیت',
    'iron.feature2.desc': 'بازرسی و کنترل کیفیت دقیق قبل از بارگیری',
    'iron.feature3.title': 'قیمت رقابتی',
    'iron.feature3.desc': 'بهترین قیمت‌های صادراتی با حذف واسطه‌ها',
    'iron.feature4.title': 'گواهی استاندارد',
    'iron.feature4.desc': 'ارائه گواهی کیفیت و استاندارد معتبر برای تمام محصولات',
    'iron.seo.title': 'صادرات آهن و فولاد | آرمان همراه',
    'iron.seo.description': 'صادرات انواع محصولات فولادی شامل میلگرد، ورق، شمش و پروفیل از برترین کارخانه‌های ایران با بهترین قیمت و کیفیت.',

    // Oil Page
    'oil.title': 'روغن‌های صنعتی و پایه',
    'oil.subtitle': 'Industrial & Base Oil',
    'oil.description': 'تأمین و صادرات انواع روغن‌های پایه و صنعتی با کیفیت بالا، مناسب برای روانکارها، گریس و سایر مصارف صنعتی از پالایشگاه‌های معتبر.',
    'oil.productsTitle': 'انواع روغن قابل تأمین',
    'oil.product1.name': 'روغن پایه (Base Oil)',
    'oil.product1.desc': 'گریدهای مختلف روغن پایه ویرجین و ریسایکل',
    'oil.product2.name': 'روغن موتور (Engine Oil)',
    'oil.product2.desc': 'روغن موتورهای بنزینی و دیزلی با استانداردهای API',
    'oil.product3.name': 'روغن هیدرولیک (Hydraulic Oil)',
    'oil.product3.desc': 'روغن هیدرولیک برای سیستم‌های صنعتی و ماشین‌آلات سنگین',
    'oil.product4.name': 'روغن دنده (Gear Oil)',
    'oil.product4.desc': 'روغن دنده برای گیربکس‌های صنعتی و خودرو',
    'oil.featuresTitle': 'ویژگی‌های محصولات ما',
    'oil.feature1.title': 'کیفیت بالا',
    'oil.feature1.desc': 'تولید با افزودنی‌های معتبر و مطابق با استانداردهای جهانی',
    'oil.feature2.title': 'آنالیز آزمایشگاهی',
    'oil.feature2.desc': 'ارائه برگه آنالیز و مشخصات فنی دقیق برای هر محصول',
    'oil.feature3.title': 'تأمین از پالایشگاه',
    'oil.feature3.desc': 'تأمین مستقیم از پالایشگاه‌های معتبر ایران',
    'oil.feature4.title': 'بسته‌بندی متنوع',
    'oil.feature4.desc': 'امکان بسته‌بندی به صورت فله، بشکه و IBC',
    'oil.seo.title': 'صادرات روغن صنعتی و پایه | آرمان همراه',
    'oil.seo.description': 'صادرات انواع روغن‌های پایه، روغن موتور، هیدرولیک و دنده از پالایشگاه‌های معتبر ایران با کیفیت تضمینی.',

    // Guarantee
    'guarantee.title': 'شرایط گارانتی ۱۸ ماهه',
    'guarantee.subtitle': 'شرکت آرمان همراه ارتباطات آریا',
    'guarantee.conditionsTitle': 'شرایط گارانتی',
    'guarantee.exceptionsTitle': 'موارد قابل اغماض',
    
    // App Section
    'app.title': 'خدمات پس از فروش در دستان شما',
    'app.description': 'شما عزیزان و همراهان آرمان همراه ارتباطات آریا با نصب اپلیکیشن آرمان من و یا استفاده از نسخه وب اپلیکیشن برای iOS از خدمات ما به صورت آنلاین بهره مند شوید.',
    'app.cta': 'ورود به آرمان من',
    
    // Representatives
    'representatives.title': 'نمایندگان فروش',
    'representatives.subtitle': 'شبکه گسترده نمایندگان آرمان همراه در سراسر ایران',
    
    // Footer
    'footer.description': 'شرکت گارانتی آرمان همراه ارتباطات آریا، ارائه دهنده خدمات گارانتی و پس از فروش برای برندهای معتبر جهانی',
    'footer.quickLinks': 'لینک‌های سریع',
    'footer.contact': 'تماس با ما',
    'footer.followUs': 'ما را دنبال کنید',
    'footer.rights': 'تمامی حقوق محفوظ است',
    
    // Theme
    'theme.light': 'روشن',
    'theme.dark': 'تاریک',

    // Product Names
    'product.apple_watch_s11.name': 'اپل واچ سری ۱۱ 46mm خاکستری',
    'product.apple_watch_se11_44.name': 'اپل واچ SE 44mm مشکی',
    'product.apple_watch_se11_44_starlight.name': 'اپل واچ SE 44mm ستاره‌ای',
    'product.apple_watch_se10_40.name': 'اپل واچ SE 40mm مشکی',
    'product.apple_watch_se10_40_silver.name': 'اپل واچ SE 40mm نقره‌ای',
    'product.airpods_pro_2.name': 'ایرپاد پرو ۲',
    'product.samsung_s25_ultra.name': 'سامسونگ S25 Ultra 256/12',
    'product.samsung_s25_fe.name': 'سامسونگ S25 FE 256/8',
    'product.samsung_a56_12.name': 'سامسونگ A56 256/12',
    'product.samsung_a56_8.name': 'سامسونگ A56 256/8',
    'product.samsung_a56_128.name': 'سامسونگ A56 128/8',
    'product.samsung_a36.name': 'سامسونگ A36 256/8',
    'product.samsung_a36_128.name': 'سامسونگ A36 128/8',
    'product.samsung_a26.name': 'سامسونگ A26 256/8',
    'product.samsung_a26_128.name': 'سامسونگ A26 128/6',
    'product.samsung_a17.name': 'سامسونگ A17 256/8',
    'product.samsung_a17_128_6.name': 'سامسونگ A17 128/6',
    'product.samsung_a17_128_4.name': 'سامسونگ A17 128/4',
    'product.samsung_a07.name': 'سامسونگ A07 128/6',
    'product.samsung_a07_128_4.name': 'سامسونگ A07 128/4',
    'product.samsung_a07_64_4.name': 'سامسونگ A07 64/4',
    'product.samsung_a06.name': 'سامسونگ A06 128/4',
    'product.samsung_tab_a9_plus.name': 'تبلت سامسونگ Galaxy Tab A9+ 128/8',
    'product.samsung_tab_a9.name': 'تبلت سامسونگ Galaxy Tab A9 64/4',
    'product.xiaomi_15t.name': 'شیائومی 15T 512/12',
    'product.redmi_note_14s.name': 'ردمی نوت 14s 256/8',
    'product.redmi_note_14_pro.name': 'ردمی نوت 14 پرو 256/8',
    'product.redmi_note_14.name': 'ردمی نوت 14 256/8',
    'product.redmi_15.name': 'ردمی 15 256/8',
    'product.redmi_15c.name': 'ردمی 15c 256/8',
    'product.redmi_13x.name': 'ردمی 13X 256/8',
    'product.redmi_a5.name': 'ردمی A5 128/4',
    'product.redmi_a3.name': 'ردمی A3 128/4',
    'product.poco_m7.name': 'پوکو M7 256/8',
    'product.poco_m6.name': 'پوکو M6 256/8',
    'product.poco_c85.name': 'پوکو C85 256/8',
    'product.poco_c85_128.name': 'پوکو C85 128/6',
    'product.poco_c75.name': 'پوکو C75 256/8',
    'product.poco_c71.name': 'پوکو C71 128/4',
    'product.nokia_105.name': 'نوکیا ۱۰۵',

    // Product Descriptions
    'product.apple_watch_s11.description': 'اپل واچ سری ۱۱ با نمایشگر همیشه روشن و بزرگ‌تر، پردازنده قدرتمند S11 و سنسورهای سلامتی پیشرفته‌تر، بهترین همراه برای زندگی سالم و متصل است. قابلیت‌های جدیدی مانند پایش دمای بدن و تشخیص تصادف، آن را به یک گجت ضروری تبدیل کرده است.',
    'product.apple_watch_se11_44.description': 'اپل واچ SE جدید، ترکیبی عالی از طراحی مدرن، قابلیت‌های کلیدی و قیمت مناسب است. این ساعت با پردازنده سریع‌تر و قابلیت تشخیص تصادف، ارزش خرید بالایی را برای کاربرانی که به دنبال اولین اپل واچ خود هستند، ارائه می‌دهد.',
    'product.apple_watch_se10_40.description': 'اپل واچ SE (2023) با طراحی زیبا و نمایشگر Retina، همراهی هوشمند برای زندگی روزمره شماست. این ساعت با قابلیت‌های پیشرفته‌ای مانند پایش ضربان قلب، تشخیص تصادف و SOS اضطراری، سلامتی و ایمنی شما را تضمین می‌کند. همچنین با دسترسی به هزاران اپلیکیشن، می‌توانید فعالیت‌های ورزشی خود را ردیابی کرده و همیشه متصل بمانید.',
    'product.airpods_pro_2.description': 'ایـرپاد پرو (نسل دوم) با قابلیت‌هایی نظیر حذف نویز فعال (Active Noise Cancellation) دو برابر قوی‌تر، حالت شفافیت تطبیق‌پذیر (Adaptive Transparency) و صدای فراگیر شخصی‌سازی‌شده (Personalized Spatial Audio)، تجربه‌ی شنیداری شما را متحول می‌کند. با یک بار شارژ تا ۶ ساعت و با کیس شارژ تا ۳۰ ساعت به موسیقی گوش دهید و با کنترل لمسی جدید، همه‌چیز را آسان‌تر مدیریت کنید.',
    'product.samsung_s25_ultra.description': 'گلکسی S25 اولترا با بهره‌گیری از هوش مصنوعی Galaxy AI، استاندارد جدیدی در دنیای موبایل تعریف می‌کند. از قابلیت Circle to Search برای جستجوی آسان‌تر گرفته تا ترجمه زنده تماس‌ها و بهبود کیفیت عکس‌ها با Photo Assist، همه چیز برای تجربه‌ای هوشمندتر آماده شده است.',
    'product.samsung_s25_fe.description': 'گلکسی S25 FE با طراحی نمادین سری S25 و رنگ‌های جذاب، تجربه‌ای پریمیوم را با قیمتی مناسب ارائه می‌دهد. دوربین باکیفیت، نمایشگر Dynamic AMOLED 2X و پردازنده قدرتمند، این گوشی را به انتخابی ایده‌آل برای طرفداران سامسونگ تبدیل کرده است.',
    'product.samsung_a56.description': 'گلکسی A56 با ترکیب فلز و شیشه، طراحی زیبا و مقاومت بالا (IP67) را به ارمغان می‌آورد. نمایشگر Super AMOLED 120Hz، دوربین 50 مگاپیکسلی و پردازنده قدرتمند، این گوشی را به گزینه‌ای عالی در میان‌رده‌ها تبدیل کرده است.',
    'product.samsung_a36.description': 'گلکسی A36 با نمایشگر خیره‌کننده Super AMOLED، دوربین سه‌گانه باکیفیت و طراحی مدرن، تجربه‌ای لذت‌بخش را برای کاربران فراهم می‌کند. این گوشی با باتری بادوام و عملکرد روان، همراهی ایده‌آл برای کارهای روزمره و سرگرمی است.',
    'product.samsung_a26.description': 'گلکسی A26 با نمایشگر 6.5 اینچی Super AMOLED و نرخ نوسازی 120 هرتز، تصاویری روان و زنده را به نمایش می‌گذارد. دوربین اصلی 50 مگاپیکسلی با لرزشگیر اپتیکال (OIS) و پردازنده 5 نانومتری، این گوشی را به ابزاری قدرتمند برای عکاسی و کارهای روزمره تبدیل کرده است.',
    'product.samsung_a17.description': 'گلکسی A17 با نمایشگر Super AMOLED، پردازنده هشت هسته‌ای و دوربین 50 مگاپیکسلی، گزینه‌ای عالی و مقرون‌به‌صرفه است. این گوشی با طراحی زیبا و باتری بادوام، نیازهای روزمره شما را به خوبی برآورده می‌کند.',
    'product.samsung_a07.description': 'گلکسی A07 با نمایشگر بزرگ 6.7 اینچی +FHD و پردازنده قدرتمند اسنپدراگون، تجربه‌ای روان و فراگیر را برای تماشا و بازی فراهم می‌کند. دوربین سه‌گانه 50 مگاپیکسلی و باتری بادوام، این گوشی را به انتخابی هوشمندانه در رده اقتصادی تبدیل کرده است.',
    'product.samsung_a06.description': 'گلکسی A06 با نمایشگر بزرگ و دوربین دوگانه 50 مگاپیکسلی، گزینه‌ای اقتصادی و کارآمد برای نیازهای اولیه است. این گوشی با پردازنده هشت هسته‌ای و باتری حجیم، عملکردی روان و طولانی‌مدت را تضمین می‌کند.',
    'product.samsung_tab_a9_plus.description': 'تبلت گلکسی Tab A9+ با نمایشگر بزرگ و روان، صدای فراگیر و عملکرد چندوظیفه‌ای قدرتمند، همراهی ایده‌آل برای سرگرمی و کارهای روزمره است. طراحی شیک و مدرن آن، تجربه‌ای لذت‌بخش را برای تمام اعضای خانواده فراهم می‌کند.',
    'product.samsung_tab_a9.description': 'تبلت گلکسی Tab A9 با طراحی کلاسیک و بدنه فلزی، در عین زیبایی، عملکردی روان را برای کارهای روزمره ارائه می‌دهد. نمایشگر روشن و بلندگوهای دوگانه، این تبلت را به گزینه‌ای عالی برای تماشای فیلم و بازی تبدیل کرده است.',
    'product.xiaomi_15t.description': 'شیائومی 15T با همکاری لایکا، تجربه‌ی عکاسی حرفه‌ای را به دنیای موبایل می‌آورد. این گوشی با پردازنده قدرتمند اسنپدراگون و نمایشگر CrystalRes AMOLED، عملکردی بی‌نظیر و تصاویری خیره‌کننده را ارائه می‌دهد.',
    'product.redmi_note_14s.description': 'ردمی نوت ۱۴ اس با دوربین ۲۰۰ مگاپیکسلی و نمایشگر 1.5K AMOLED، تصاویری با وضوح و کیفیت بی‌نظیر ثبت می‌کند. این گوشی با پردازنده اسنپدراگون و طراحی مقاوم، انتخابی هوشمندانه برای کاربرانی است که به دنبال بهترین‌ها هستند.',
    'product.redmi_note_14_pro.description': 'ردمی نوت ۱۴ پرو با دوربین ۲۰۰ مگاپیکسلی و لرزشگیر اپتیکال، عکاسی را در سطح پرچمداران ارائه می‌دهد. نمایشگر 1.5K AMOLED با نرخ نوسازی 120 هرتز و شارژ فوق سریع 120 وات، این گوشی را به یک هیولای تمام‌عیار تبدیل کرده است.',
    'product.redmi_note_14.description': 'ردمی نوت ۱۴ با دوربین سه‌گانه ۱۰۸ مگاپیکسلی و نمایشگر خیره‌کننده AMOLED با حاشیه‌های بسیار باریک، تجربه‌ای بصری فوق‌العاده را به ارمغان می‌آورد. طراحی شیک و پردازنده قدرتمند، آن را به گزینه‌ای جذاب در بازار میان‌رده‌ها تبدیل کرده است.',
    'product.redmi_15.description': 'ردمی ۱۵ با دوربین اصلی ۱۰۸ مگاپیکسلی و زوم 3X، عکاسی با جزئیات خیره‌کننده را ممکن می‌سازد. نمایشگر FHD+ با تکنولوژی AdaptiveSync و باتری قدرتمند، تجربه‌ای روان و طولانی‌مدت را برای شما رقم می‌زند.',
    'product.redmi_15c.description': 'ردمی 15C با نمایشگر روان 90 هرتزی و دوربین دوگانه هوش مصنوعی 50 مگاپیکسلی، ترکیبی از کارایی و زیبایی را با قیمتی مناسب ارائه می‌دهد. این گوشی با پردازنده هشت هسته‌ای مدیاتک، عملکردی قابل اعتماد را برای تمام نیازهای شما تضمین می‌کند.',
    'product.redmi_a3.description': 'ردمی A3 شیائومی با طراحی پریمیوم و شیشه‌ای، نمایشگر بزرگ 6.71 اینچی با نرخ نوسازی 90 هرتز و قیمتی اقتصادی، تجربه‌ای فراتر از انتظار را به کاربران ارائه می‌دهد. این گوشی هوشمند، انتخابی عالی برای کسانی است که به دنبال زیبایی و کارایی در یک پکیج مقرون‌به‌صرفه هستند.',
    'product.poco_m6.description': 'پوکو M6 پرو با اولین نمایشگر Flow AMOLED در سری M و نرخ نوسازی ۱۲۰ هرتز، تجربه‌ای بی‌نظیر از تماشا و بازی را ارائه می‌دهد. شارژ سریع ۶۷ واتی، دوربین ۶۴ مگاپیکسلی با لرزشگیر اپتیکال و پردازنده قدرتمند Helio G99-Ultra، این گوشی را به گزینه‌ای بی‌رقیب تبدیل کرده است.',
    'product.nokia_105.description': 'نوکیا ۱۰۵ (۲۰۲۳) با طراحی مدرن، عمر باتری طولانی و بدنه‌ای مقاوم، یک گوشی کلاسیک و قابل اعتماد برای مکالمات روزمره است. این گوشی با قابلیت‌هایی مانند رادیو FM بی‌سیم و چراغ قوه، همراهی کاربردی برای شما خواهد بود.',

    // Product Specs - Keys
    'spec.display': 'نمایشگر',
    'spec.cpu': 'پردازنده',
    'spec.ram': 'رم',
    'spec.internal_storage': 'حافظه داخلی',
    'spec.main_camera': 'دوربین اصلی',
    'spec.battery': 'باتری',
    'spec.water_resistance': 'مقاومت در برابر آب',
    'spec.sensors': 'سنسورها',
    'spec.features': 'قابلیت‌ها',
    'spec.connectivity': 'اتصالات',
    'spec.chip': 'تراشه',
    'spec.noise_cancellation': 'حذف نویز',
    'spec.transparency_mode': 'حالت شفافیت',
    'spec.spatial_audio': 'صدای فراگیر',
    'spec.microphones': 'میکروفون‌ها',
    'spec.resistance': 'مقاومت',
    'spec.battery_earbuds': 'عمر باتری (ایربادها)',
    'spec.battery_case': 'عمر باتری (با کیس)',
    'spec.pen': 'قلم',
    'spec.security': 'امنیت',
    'spec.os': 'سیستم عامل',
    'spec.sound': 'صدا',
    'spec.fingerprint': 'حسگر اثر انگشت',
    'spec.port': 'درگاه',
    'spec.sim': 'سیم‌کارت',

    // Product Specs - Values
    'spec.value.retina_ltpo_oled_always_on': 'Retina LTPO OLED همیشه روشن',
    'spec.value.water_resistance_50m': 'مقاوم در برابر آب تا عمق ۵۰ متر',
    'spec.value.sensors_s11': 'سنسور اکسیژن خون، سنسور ضربان قلب الکتریکی و اپتیکال، سنسور دمای بدن',
    'spec.value.features_s11': 'تشخیص تصادف، تشخیص سقوط، SOS اضطراری بین‌المللی',
    'spec.value.battery_s11': 'تا ۱۸ ساعت (تا ۳۶ ساعت در حالت Low Power)',
    'spec.value.connectivity_s11': 'Wi-Fi, Bluetooth 5.3, GPS, Cellular',
    'spec.value.retina_ltpo_oled': 'Retina LTPO OLED',
    'spec.value.sensors_se11': 'سنسور ضربان قلب اپتیکال نسل دوم، شتاب‌سنج، ژیروسکوپ، ارتفاع‌سنج',
    'spec.value.features_se': 'تشخیص تصادف، تشخیص سقوط، SOS اضطراری',
    'spec.value.battery_18h': 'تا ۱۸ ساعت',
    'spec.value.connectivity_se': 'Wi-Fi, Bluetooth 5.3, GPS',
    'spec.value.sensors_se10': 'سنسور ضربان قلب اپتیکال نسل دوم، شتاب‌سنج، ژیروسکوپ، ارتفاع‌سنج، قطب‌نما',
    'spec.value.features_se_sleep': 'تشخیص تصادف، تشخیص سقوط، SOS اضطراری، پایش خواب',
    'spec.value.active_noise_cancellation': 'حذف نویز فعال (Active Noise Cancellation)',
    'spec.value.adaptive_transparency': 'شفافیت تطبیق‌پذیر (Adaptive Transparency)',
    'spec.value.personalized_spatial_audio': 'صدای فراگیر شخصی‌سازی‌شده با ردیابی پویای سر',
    'spec.value.dual_beamforming_mics': 'میکروفون‌های دوگانه با قابلیت beamforming',
    'spec.value.sensors_airpods_pro_2': 'سنسور تشخیص پوست، شتاب‌سنج تشخیص حرکت و گفتار، کنترل لمسی',
    'spec.value.resistance_ipx4': 'مقاوم در برابر تعریق و آب (IPX4)',
    'spec.value.battery_airpods_6h': 'تا ۶ ساعت پخش موسیقی با یک بار شارژ',
    'spec.value.battery_airpods_30h': 'تا ۳۰ ساعت پخش موسیقی',
    'spec.value.display_dynamic_amoled_6_8': 'Dynamic AMOLED 2X, 120Hz, HDR10+, 6.8 inches',
    'spec.value.camera_s25_ultra': '200MP (واید) + 50MP (پریسکوپ تله‌فوتو) + 10MP (تله‌فوتو) + 12MP (اولتراواید)',
    'spec.value.battery_5000mah_45w': '5000 میلی‌آمپر ساعت، شارژ سریع 45 وات',
    'spec.value.spen_ai': 'S Pen داخلی با پشتیبانی از هوش مصنوعی',
    'spec.value.display_dynamic_amoled_6_4': 'Dynamic AMOLED 2X, 120Hz, 6.4 inches',
    'spec.value.camera_s25_fe': '50MP (واید) + 8MP (تله‌فوتو) + 12MP (اولتراواید)',
    'spec.value.battery_4500mah_25w': '4500 میلی‌آمپر ساعت، شارژ سریع 25 وات',
    'spec.value.resistance_ip68': 'مقاوم در برابر آب و گرد و غبار (IP68)',
    'spec.value.display_super_amoled_6_6': 'Super AMOLED, 120Hz, 6.6 inches',
    'spec.value.camera_a56': '50MP (واید) + 12MP (اولتراواید) + 5MP (ماکرو)',
    'spec.value.battery_5000mah_25w': '5000 میلی‌آمپر ساعت، شارژ سریع 25 وات',
    'spec.value.display_super_amoled_6_6_120hz': 'Super AMOLED, 120Hz, 6.6 inches',
    'spec.value.camera_a36': '50MP (واید) + 8MP (اولتراواید) + 5MP (ماکرو)',
    'spec.value.resistance_ip67': 'مقاوم در برابر آب و گرد و غبار (IP67)',
    'spec.value.display_super_amoled_6_5_120hz': 'Super AMOLED, 120Hz, 6.5 inches',
    'spec.value.camera_a26': '50MP (واید) OIS + 8MP (اولتراواید) + 2MP (ماکرو)',
    'spec.value.display_super_amoled_6_5_90hz': 'Super AMOLED, 90Hz, 6.5 inches',
    'spec.value.camera_a17': '50MP (واید) + 5MP (اولتراواید) + 2MP (ماکرو)',
    'spec.value.display_pls_lcd_6_7_90hz': 'PLS LCD, 90Hz, 6.7 inches',
    'spec.value.camera_a07': '50MP (واید) + 2MP (ماکرو) + 2MP (سنسور عمق)',
    'spec.value.display_pls_lcd_6_7': 'PLS LCD, 6.7 inches',
    'spec.value.camera_a06': '50MP (واید) + 2MP (سنسور عمق)',
    'spec.value.display_tft_lcd_11_90hz': 'TFT LCD, 90Hz, 11.0 inches',
    'spec.value.sound_quad_dolby_atmos': 'چهار بلندگو با پشتیبانی از Dolby Atmos',
    'spec.value.display_tft_lcd_8_7': 'TFT LCD, 8.7 inches',
    'spec.value.display_crystalres_amoled_6_36': 'CrystalRes AMOLED, 120Hz, Dolby Vision, 6.36 inches',
    'spec.value.camera_xiaomi_15t': 'دوربین اصلی لایکا 50MP + تله‌فوتو لایکا 50MP + اولتراواید لایکا 50MP',
    'spec.value.battery_4610mah_90w': '4610 میلی‌آمپر ساعت، شارژ سریع 90 وات HyperCharge',
    'spec.value.display_1_5k_amoled_6_67': '1.5K AMOLED, 120Hz, 6.67 inches',
    'spec.value.camera_redmi_note_14s': '200MP (واید) OIS + 8MP (اولتراواید) + 2MP (ماکرو)',
    'spec.value.battery_5100mah_67w': '5100 میلی‌آمپر ساعت، شارژ سریع 67 وات',
    'spec.value.display_1_5k_crystalres_amoled_6_67': '1.5K CrystalRes AMOLED, 120Hz, 6.67 inches',
    'spec.value.camera_redmi_note_14_pro': '200MP (واید) OIS + 8MP (اولتراواید) + 2MP (ماکرو)',
    'spec.value.battery_5000mah_120w': '5000 میلی‌آمپر ساعت، شارژ سریع 120 وات HyperCharge',
    'spec.value.display_amoled_6_67_120hz': 'AMOLED, 120Hz, 6.67 inches',
    'spec.value.camera_redmi_note_14': '108MP (واید) + 8MP (اولتراواید) + 2MP (سنسور عمق)',
    'spec.value.battery_5000mah_33w': '5000 میلی‌آمپر ساعت، شارژ سریع 33 وات',
    'spec.value.display_fhd_plus_amoled_6_79_90hz': 'FHD+ AMOLED, 90Hz AdaptiveSync, 6.79 inches',
    'spec.value.camera_redmi_15': '108MP (واید) + 2MP (ماکرو)',
    'spec.value.battery_5030mah_33w': '5030 میلی‌آمپر ساعت، شارژ سریع 33 وات',
    'spec.value.display_ips_lcd_6_74_90hz': 'IPS LCD, 90Hz, 6.74 inches',
    'spec.value.camera_redmi_15c': '50MP (واید) + 2MP (ماکرو)',
    'spec.value.battery_5000mah_18w': '5000 میلی‌آمپر ساعت، شارژ سریع 18 وات',
    'spec.value.display_ips_lcd_6_71_90hz': '6.71 اینچ, IPS LCD, 90Hz',
    'spec.value.display_flow_amoled_6_67_120hz': 'Flow AMOLED, 120Hz, 6.67 inches',
    'spec.value.camera_poco_m6': '64MP (واید) OIS + 8MP (اولتراواید) + 2MP (ماکرو)',
    'spec.value.battery_5000mah_67w': '5000 میلی‌آمپر ساعت، شارژ سریع 67 وات',
    'spec.value.fingerprint_under_display': 'زیر نمایشگر',
    'spec.value.features_nokia_105': 'رادیو FM (بی‌سیم و باسیم)، چراغ قوه، بازی‌های کلاسیک',
  },
  en: {
    // General
    'all': 'All',
    'product.coming_soon': 'Product information will be available soon.',

    // Brands
    'Apple': 'Apple',
    'Samsung': 'Samsung',
    'Xiaomi': 'Xiaomi',
    'Poco': 'Poco',
    'Nokia': 'Nokia',

    // Categories
    'category.mobile': 'Mobile',
    'category.smartwatch': 'Smartwatch',
    'category.tablet': 'Tablet',
    'category.accessories': 'Accessories',
    'category.feature_phone': 'Feature Phone',

    // Navigation
    'nav.home': 'Home',
    'nav.warranty': 'Arman Warranty',
    'nav.products': 'Products',
    'nav.export': 'Export',
    'nav.representatives': 'Representatives',
    'nav.blog': 'Blog & Training',
    'nav.contact': 'Contact Us',
    'nav.myArman': 'Register',
    'nav.cooperation': 'Cooperation',
    
    // Hero
    'hero.title': 'The Smartest Warranty & Services',
    'hero.subtitle': 'After-Sales in Iran',
    'hero.description': 'Arman Hamrah Aria Communications Warranty Company has been providing the best customer service experience since 2014',
    'hero.cta': 'Our Services',
    'hero.cta2': 'Register',
    
    // Brands
    'brands.title': 'Covered Brands',
    
    // Services
    'services.title': 'Our Services',
    'services.warranty.title': 'Arman Warranty',
    'services.warranty.desc': 'Valid warranty for Apple, Samsung, Xiaomi and Sony products',
    'services.representatives.title': 'Representatives',
    'services.representatives.desc': 'Our extensive network of representatives across Iran',
    'services.shop.title': 'Shop',
    'services.shop.desc': 'Buy original products with valid warranty',
    'services.export.title': 'Export',
    'services.export.desc': 'Exporting products worldwide',

    // Subsidiaries
    'subsidiaries.title': 'Subsidiary Companies',
    'subsidiary.1.name': 'Aein Tejarat Aran',
    'subsidiary.2.name': 'Arsha Fanavaran Radan',
    'subsidiary.3.name': 'Arta Tejarat Keyhan',
    'subsidiary.4.name': 'Farnam Tejarat Dadar',
    'subsidiary.5.name': 'Danial Tejarat Dara',
    'subsidiary.6.name': 'Farnam Tejarat Kara',
    'subsidiary.7.name': 'Karzin Tejarat Arshan',
    'subsidiary.8.name': 'Mania Tejarat Makan',
    'subsidiary.9.name': 'Karzin Tejarat Arshan',
    'subsidiary.10.name': 'Radical One',

    // Products Page
    'products.title': 'Products',
    'products.back': 'Back to Home',
    'products.back_to_list': 'Back to Products',
    'products.description': 'All products come with a valid Arman Hamrah Communications Aria warranty',
    'products.brand': 'Brand:',
    'products.category': 'Category:',
    'products.view': 'View',
    'products.noProducts': 'No products found',
    'products.not_found': 'Product not found',
    'products.intro': 'Product Introduction',
    'products.specs': 'Specifications',
    'products.specs_soon': 'Specifications for this product will be added soon.',
    'products.seo.title': 'Products | Arman Hamrah Communications Aria',
    'products.seo.description': 'View all Apple, Samsung products with Arman Hamrah warranty - iPhone, Galaxy, Apple Watch and smartwatches',

    // Export Page
    'export.back': 'Back to Export Page',
    'export.title_main': 'Arman Export',
    'export.subtitle_main': 'Best Solution for importing goods from IRAN',
    'export.description_main': 'With over 9 years of experience, Arman Company has successfully engaged in importing and exporting basic and specialized goods in various sectors including IT, food, clothing, petroleum, metals, and construction materials.',
    'export.features.title': 'Export Services Features',
    'export.features.international.title': 'International Export',
    'export.features.international.description': 'Exporting products to Middle East, Central Asia and neighboring countries',
    'export.features.transportation.title': 'Safe Transportation',
    'export.features.transportation.description': 'Safe shipping with full insurance and online tracking at all stages',
    'export.features.original.title': 'Original Products',
    'export.features.original.description': 'Guarantee of product authenticity with valid international warranty and certificate of authenticity',
    'export.features.documentation.title': 'Complete Documentation',
    'export.features.documentation.description': 'Preparation of all customs documents, export permits, and necessary licenses',
    'export.products.title': 'Export Products',
    'export.products.view_details': 'View Details',
    'export.products.category.metals': 'Metals',
    'export.products.category.petrochemical': 'Petrochemical',
    'export.products.category.textile': 'Textile',
    'export.products.iron_steel.name': 'Iron and Steel',
    'export.products.iron_steel.description': 'The best and highest quality Iron and Steel in the IRAN market.',
    'export.products.copper_rod.name': 'Copper Rod',
    'export.products.copper_rod.description': 'The best and highest quality Copper Rod in the IRAN market.',
    'export.products.bitumen.name': 'Bitumen',
    'export.products.bitumen.description': 'The best and highest quality Bitumen in the IRAN market.',
    'export.products.oil.name': 'Oil',
    'export.products.oil.description': 'The best and highest quality industrial and base oils in the IRAN market.',
    'export.products.thread.name': 'Thread',
    'export.products.thread.description': 'The best and highest quality Thread in the IRAN market.',
    'export.services.title': 'Our Export Services',
    'export.services.packaging.title': 'Export Packaging',
    'export.services.packaging.description': 'Standard and professional packaging according to international standards',
    'export.services.clearance.title': 'Customs Clearance',
    'export.services.clearance.description': 'All customs affairs and cargo clearance at origin and destination',
    'export.services.quality.title': 'Quality Guarantee',
    'export.services.quality.description': 'Inspection and quality control of all products before shipment',
    'export.goal.title': 'Our Goal',
    'export.goal.description': 'With over 9 years of experience, Arman Company has successfully engaged in importing and exporting basic and specialized goods in various sectors including IT, food, clothing, petroleum, metals, and construction materials. The company’s purpose is to establish extensive business connections worldwide.',
    'export.countries.title': 'Target Export Countries',
    'export.countries.subtitle': 'Export to regional and neighboring countries',
    'country.uae': 'UAE',
    'country.iraq': 'Iraq',
    'country.afghanistan': 'Afghanistan',
    'country.turkmenistan': 'Turkmenistan',
    'country.azerbaijan': 'Azerbaijan',
    'country.armenia': 'Armenia',
    'country.qatar': 'Qatar',
    'country.kuwait': 'Kuwait',
    'export.contact.title': 'Contact Us',
    'export.contact.subtitle': 'For More Information Contact Our Specialist',
    'export.contact.phone': 'Phone',
    'export.contact.address': 'Address',
    'export.contact.address_value': 'Unit 304, 3rd Floor, Amir Atabak Building, Soleyman Khater St, Motahari St, Tehran, IRAN',
    'export.form.title': 'Contact Form',
    'export.form.full_name': 'Full Name',
    'export.form.full_name_placeholder': 'Your full name',
    'export.form.company_name': 'Company Name',
    'export.form.company_name_placeholder': 'Your company name',
    'export.form.message': 'Your Message',
    'export.form.message_placeholder': 'How can we help you?',
    'export.form.send': 'Send Message',
    'export.cta.title': 'Start Your Business With Us',
    'export.cta.subtitle': 'Our commercial experts are always striving to enhance convenience for your business.',
    'export.cta.button_start': 'Start Conversation',
    'export.seo.title': 'Export | Best Solution for importing goods from IRAN',
    'export.seo.description': 'Export services for products to regional countries - Iron and Steel, Copper Rod, Bitumen, Oil, and Thread',
    
    // Bitumen Page
    'bitumen.title': 'Bitumen',
    'bitumen.subtitle': 'Bitumen',
    'bitumen.category': 'Petrochemical',
    'bitumen.description': 'The best and highest quality bitumen in the Iranian market, produced in reputable refineries and in accordance with international standards.',
    'bitumen.gradesTitle': 'Available Grades',
    'bitumen.specsTitle': 'Product Specifications',
    'bitumen.feature1.title': 'Refinery Production',
    'bitumen.feature1.desc': 'Produced in reputable Iranian refineries',
    'bitumen.feature2.title': 'Guaranteed Quality',
    'bitumen.feature2.desc': 'Quality assurance with international standards',
    'bitumen.feature3.title': 'Certifications',
    'bitumen.feature3.desc': 'Compliant with ASTM standards',
    'bitumen.feature4.title': 'Complete Documentation',
    'bitumen.feature4.desc': 'All necessary documents and certificates provided',
    'bitumen.table.characteristic': 'Characteristic',
    'bitumen.table.unit': 'Unit',
    'bitumen.table.specification': 'Specification',
    'bitumen.table.testMethod': 'Test Method',
    'bitumen.spec.penetration': 'Penetration @25°C',
    'bitumen.spec.specificGravity': 'Specific Gravity @25°C',
    'bitumen.spec.softeningPoint': 'Softening Point',
    'bitumen.spec.ductility': 'Ductility @25°C',
    'bitumen.spec.lossOnHeating': 'Loss on Heating',
    'bitumen.spec.dropInPenetration': 'Drop in Penetration after Heating',
    'bitumen.spec.flashPoint': 'Flash Point',
    'bitumen.spec.solubility': 'Solubility in CS2',
    'bitumen.seo.title': 'Bitumen Export | Arman Hamrah',
    'bitumen.seo.description': 'Export of the best and highest quality Iranian bitumen in various grades (60/70, VG10, VG30) with quality assurance and international standards.',

    // Copper Rod Page
    'copper.title': 'Copper Rod',
    'copper.subtitle': 'مفتول مسی',
    'copper.description': 'Export of high-quality copper rod with 99.9% purity, produced according to global standards for the cable and wire industries.',
    'copper.featuresTitle': 'Copper Rod Features',
    'copper.feature1.title': 'High Flexibility',
    'copper.feature1.desc': 'Suitable for various industrial and construction applications',
    'copper.feature2.title': 'Excellent Electrical Conductivity',
    'copper.feature2.desc': 'Ensures minimal energy loss in power transmission',
    'copper.feature3.title': 'Global Standard',
    'copper.feature3.desc': 'Manufactured in accordance with ASTM B49 standard',
    'copper.feature4.title': 'Secure Packaging',
    'copper.feature4.desc': 'Complete protection against oxidation and damage',
    'copper.specsTitle': 'Copper Rod Specifications',
    'copper.table.characteristic': 'Characteristic',
    'copper.table.value': 'Value',
    'copper.spec.diameter': 'Diameter',
    'copper.spec.conductivity': 'Electrical Conductivity',
    'copper.spec.tensile': 'Tensile Strength',
    'copper.spec.elongation': 'Elongation',
    'copper.spec.purity': 'Purity',
    'copper.spec.standard': 'Standard',
    'copper.seo.title': 'Copper Rod Export | Arman Hamrah',
    'copper.seo.description': 'Export of 99.9% purity copper rod with high electrical conductivity, compliant with ASTM B49 standard for cable industries.',

    // Iron & Steel Page
    'iron.title': 'Iron & Steel',
    'iron.subtitle': 'آهن و فولاد',
    'iron.description': 'Supply and export of various steel products including rebar, sheets, billets, and structural profiles with the best quality from reputable Iranian factories.',
    'iron.productsTitle': 'Available Products',
    'iron.product1.name': 'Rebar',
    'iron.product1.desc': 'Deformed and plain rebar in various sizes',
    'iron.product2.name': 'Steel Sheet',
    'iron.product2.desc': 'Hot-rolled, cold-rolled, galvanized, and colored sheets',
    'iron.product3.name': 'Billet/Bloom/Slab',
    'iron.product3.desc': 'Various types of steel billets for rolling applications',
    'iron.product4.name': 'Beam',
    'iron.product4.desc': 'IPE, IPB, and H-beams in standard sizes',
    'iron.product5.name': 'Profile',
    'iron.product5.desc': 'Various types of structural and industrial box profiles',
    'iron.product6.name': 'Angle/Channel',
    'iron.product6.desc': 'Steel angles and channels in various dimensions',
    'iron.featuresTitle': 'Why Iranian Iron & Steel?',
    'iron.feature1.title': 'Top Producers',
    'iron.feature1.desc': 'Sourced from the largest and most reputable steel factories in Iran',
    'iron.feature2.title': 'Quality Control',
    'iron.feature2.desc': 'Strict quality control and inspection before loading',
    'iron.feature3.title': 'Competitive Pricing',
    'iron.feature3.desc': 'Best export prices by eliminating intermediaries',
    'iron.feature4.title': 'Standard Certification',
    'iron.feature4.desc': 'Provision of valid quality and standard certificates for all products',
    'iron.seo.title': 'Iron & Steel Export | Arman Hamrah',
    'iron.seo.description': 'Export of various steel products including rebar, sheets, billets, and profiles from top Iranian factories at the best price and quality.',

    // Oil Page
    'oil.title': 'Industrial & Base Oil',
    'oil.subtitle': 'روغن‌های صنعتی و پایه',
    'oil.description': 'Supply and export of high-quality base and industrial oils, suitable for lubricants, grease, and other industrial applications from reputable refineries.',
    'oil.productsTitle': 'Available Oil Types',
    'oil.product1.name': 'Base Oil',
    'oil.product1.desc': 'Various grades of virgin and recycled base oil',
    'oil.product2.name': 'Engine Oil',
    'oil.product2.desc': 'Gasoline and diesel engine oils with API standards',
    'oil.product3.name': 'Hydraulic Oil',
    'oil.product3.desc': 'Hydraulic oil for industrial systems and heavy machinery',
    'oil.product4.name': 'Gear Oil',
    'oil.product4.desc': 'Gear oil for industrial and automotive gearboxes',
    'oil.featuresTitle': 'Our Product Features',
    'oil.feature1.title': 'High Quality',
    'oil.feature1.desc': 'Produced with reputable additives and compliant with global standards',
    'oil.feature2.title': 'Laboratory Analysis',
    'oil.feature2.desc': 'Provision of analysis sheets and detailed technical specifications for each product',
    'oil.feature3.title': 'Refinery Sourced',
    'oil.feature3.desc': 'Directly sourced from reputable Iranian refineries',
    'oil.feature4.title': 'Flexible Packaging',
    'oil.feature4.desc': 'Available in bulk, drum, and IBC packaging',
    'oil.seo.title': 'Industrial & Base Oil Export | Arman Hamrah',
    'oil.seo.description': 'Export of various base oils, engine oil, hydraulic, and gear oil from reputable Iranian refineries with guaranteed quality.',

    // Guarantee
    'guarantee.title': '18-Month Warranty Terms',
    'guarantee.subtitle': 'Arman Hamrah Aria Communications Company',
    'guarantee.conditionsTitle': 'Warranty Conditions',
    'guarantee.exceptionsTitle': 'Acceptable Exceptions',
    
    // App Section
    'app.title': 'After-Sales Service at Your Fingertips',
    'app.description': 'Dear customers of Arman Hamrah Aria Communications, enjoy our online services by installing the My Arman app or using the web version for iOS.',
    'app.cta': 'Login to My Arman',
    
    // Representatives
    'representatives.title': 'Sales Representatives',
    'representatives.subtitle': 'Our extensive network across Iran',
    
    // Footer
    'footer.description': 'Arman Hamrah Aria Communications Warranty Company, providing warranty and after-sales services for prestigious global brands',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact Us',
    'footer.followUs': 'Follow Us',
    'footer.rights': 'All rights reserved',
    
    // Theme
    'theme.light': 'Light',
    'theme.dark': 'Dark',

    // Product Names
    'product.apple_watch_s11.name': 'Apple Watch S11 46mm Gray',
    'product.apple_watch_se11_44.name': 'Apple Watch SE 44mm Black',
    'product.apple_watch_se11_44_starlight.name': 'Apple Watch SE 44mm Starlight',
    'product.apple_watch_se10_40.name': 'Apple Watch SE 40mm Black',
    'product.apple_watch_se10_40_silver.name': 'Apple Watch SE 40mm Silver',
    'product.airpods_pro_2.name': 'AirPods Pro 2',
    'product.samsung_s25_ultra.name': 'Samsung S25 Ultra 256/12',
    'product.samsung_s25_fe.name': 'Samsung S25 FE 256/8',
    'product.samsung_a56_12.name': 'Samsung A56 256/12',
    'product.samsung_a56_8.name': 'Samsung A56 256/8',
    'product.samsung_a56_128.name': 'Samsung A56 128/8',
    'product.samsung_a36.name': 'Samsung A36 256/8',
    'product.samsung_a36_128.name': 'Samsung A36 128/8',
    'product.sAMSUNG_A26.name': 'Samsung A26 256/8',
    'product.samsung_a26_128.name': 'Samsung A26 128/6',
    'product.samsung_a17.name': 'Samsung A17 256/8',
    'product.samsung_a17_128_6.name': 'Samsung A17 128/6',
    'product.samsung_a17_128_4.name': 'Samsung A17 128/4',
    'product.samsung_a07.name': 'Samsung A07 128/6',
    'product.samsung_a07_128_4.name': 'Samsung A07 128/4',
    'product.samsung_a07_64_4.name': 'Samsung A07 64/4',
    'product.samsung_a06.name': 'Samsung A06 128/4',
    'product.samsung_tab_a9_plus.name': 'Samsung Galaxy Tab A9+ 128/8',
    'product.samsung_tab_a9.name': 'Samsung Galaxy Tab A9 64/4',
    'product.xiaomi_15t.name': 'Xiaomi 15T 512/12',
    'product.redmi_note_14s.name': 'Redmi Note 14s 256/8',
    'product.redmi_note_14_pro.name': 'Redmi Note 14 Pro 256/8',
    'product.redmi_note_14.name': 'Redmi Note 14 256/8',
    'product.redmi_15.name': 'Redmi 15 256/8',
    'product.redmi_15c.name': 'Redmi 15c 256/8',
    'product.redmi_13x.name': 'Redmi 13X 256/8',
    'product.redmi_a5.name': 'Redmi A5 128/4',
    'product.redmi_a3.name': 'Redmi A3 128/4',
    'product.poco_m7.name': 'Poco M7 256/8',
    'product.poco_m6.name': 'Poco M6 256/8',
    'product.poco_c85.name': 'Poco C85 256/8',
    'product.poco_c85_128.name': 'Poco C85 128/6',
    'product.poco_c75.name': 'Poco C75 256/8',
    'product.poco_c71.name': 'Poco C71 128/4',
    'product.nokia_105.name': 'Nokia 105',

    // Product Descriptions
    'product.apple_watch_s11.description': 'The Apple Watch Series 11 features a larger, always-on display, a powerful S11 processor, and more advanced health sensors, making it the best companion for a healthy and connected life. New features like body temperature monitoring and crash detection make it an essential gadget.',
    'product.apple_watch_se11_44.description': 'The new Apple Watch SE is a great combination of modern design, key features, and an affordable price. With a faster processor and crash detection, it offers great value for users looking for their first Apple Watch.',
    'product.apple_watch_se10_40.description': 'The Apple Watch SE (2023) with its beautiful design and Retina display is a smart companion for your daily life. With advanced features like heart rate monitoring, crash detection, and Emergency SOS, it ensures your health and safety. You can also track your workouts and stay connected with access to thousands of apps.',
    'product.airpods_pro_2.description': 'AirPods Pro (2nd generation) revolutionize your listening experience with features like twice as strong Active Noise Cancellation, Adaptive Transparency, and Personalized Spatial Audio. Listen to music for up to 6 hours on a single charge and up to 30 hours with the charging case, and manage everything easier with the new touch control.',
    'product.samsung_s25_ultra.description': 'The Galaxy S25 Ultra, powered by Galaxy AI, sets a new standard in the mobile world. From the Circle to Search feature for easier searching to live translation of calls and improved photo quality with Photo Assist, everything is ready for a smarter experience.',
    'product.samsung_s25_fe.description': 'The Galaxy S25 FE, with the iconic design of the S25 series and attractive colors, offers a premium experience at an affordable price. A high-quality camera, Dynamic AMOLED 2X display, and powerful processor make this phone an ideal choice for Samsung fans.',
    'product.samsung_a56.description': 'The Galaxy A56 combines metal and glass for a beautiful and durable design (IP67). A Super AMOLED 120Hz display, 50MP camera, and powerful processor make this phone a great mid-range option.',
    'product.samsung_a36.description': 'The Galaxy A36 provides a delightful experience with its stunning Super AMOLED display, high-quality triple camera, and modern design. With a durable battery and smooth performance, this phone is an ideal companion for daily tasks and entertainment.',
    'product.samsung_a26.description': 'The Galaxy A26 displays smooth and vivid images with its 6.5-inch Super AMOLED display and 120Hz refresh rate. The 50MP main camera with optical image stabilization (OIS) and a 5nm processor make this phone a powerful tool for photography and daily tasks.',
    'product.samsung_a17.description': 'The Galaxy A17 is an excellent and affordable option with its Super AMOLED display, octa-core processor, and 50MP camera. With a beautiful design and durable battery, this phone meets your daily needs well.',
    'product.samsung_a07.description': 'The Galaxy A07 provides a smooth and immersive experience for watching and gaming with its large 6.7-inch FHD+ display and powerful Snapdragon processor. A 50MP triple camera and durable battery make this phone a smart choice in the budget category.',
    'product.samsung_a06.description': 'The Galaxy A06 is an economical and efficient option for basic needs with its large display and 50MP dual camera. With an octa-core processor and a large battery, this phone ensures smooth and long-lasting performance.',
    'product.samsung_tab_a9_plus.description': 'The Galaxy Tab A9+ is an ideal companion for entertainment and daily tasks with its large and smooth display, immersive sound, and powerful multitasking performance. Its stylish and modern design provides a delightful experience for the whole family.',
    'product.samsung_tab_a9.description': 'The Galaxy Tab A9, with its classic design and metal body, offers smooth performance for daily tasks while being beautiful. A bright display and dual speakers make this tablet a great option for watching movies and playing games.',
    'product.xiaomi_15t.description': 'The Xiaomi 15T, in collaboration with Leica, brings a professional photography experience to the mobile world. With a powerful Snapdragon processor and CrystalRes AMOLED display, this phone delivers outstanding performance and stunning visuals.',
    'product.redmi_note_14s.description': 'The Redmi Note 14s captures images with unparalleled clarity and quality with its 200MP camera and 1.5K AMOLED display. With a Snapdragon processor and durable design, this phone is a smart choice for users looking for the best.',
    'product.redmi_note_14_pro.description': 'The Redmi Note 14 Pro offers flagship-level photography with its 200MP camera and optical image stabilization. A 1.5K AMOLED display with a 120Hz refresh rate and 120W ultra-fast charging make this phone a true beast.',
    'product.redmi_note_14.description': 'The Redmi Note 14 provides an extraordinary visual experience with its 108MP triple camera and stunning AMOLED display with ultra-thin bezels. Its stylish design and powerful processor make it an attractive option in the mid-range market.',
    'product.redmi_15.description': 'The Redmi 15 enables photography with stunning detail with its 108MP main camera and 3X zoom. The FHD+ display with AdaptiveSync technology and a powerful battery provide a smooth and long-lasting experience.',
    'product.redmi_15c.description': 'The Redmi 15C offers a combination of performance and beauty at an affordable price with its smooth 90Hz display and 50MP AI dual camera. With a MediaTek octa-core processor, this phone ensures reliable performance for all your needs.',
    'product.redmi_a3.description': 'The Xiaomi Redmi A3 offers a beyond-expectation experience with its premium glass design, large 6.71-inch display with 90Hz refresh rate, and an economical price. This smartphone is an excellent choice for those looking for beauty and performance in an affordable package.',
    'product.poco_m6.description': 'The Poco M6 Pro offers an unparalleled viewing and gaming experience with the first Flow AMOLED display in the M series and a 120Hz refresh rate. 67W fast charging, a 64MP camera with OIS, and a powerful Helio G99-Ultra processor make this phone an unbeatable option.',
    'product.nokia_105.description': 'The Nokia 105 (2023) is a classic and reliable phone for daily calls with its modern design, long battery life, and durable body. With features like a wireless FM radio and flashlight, this phone will be a practical companion for you.',

    // Product Specs - Keys
    'spec.display': 'Display',
    'spec.cpu': 'CPU',
    'spec.ram': 'RAM',
    'spec.internal_storage': 'Internal Storage',
    'spec.main_camera': 'Main Camera',
    'spec.battery': 'Battery',
    'spec.water_resistance': 'Water Resistance',
    'spec.sensors': 'Sensors',
    'spec.features': 'Features',
    'spec.connectivity': 'Connectivity',
    'spec.chip': 'Chip',
    'spec.noise_cancellation': 'Noise Cancellation',
    'spec.transparency_mode': 'Transparency Mode',
    'spec.spatial_audio': 'Spatial Audio',
    'spec.microphones': 'Microphones',
    'spec.resistance': 'Resistance',
    'spec.battery_earbuds': 'Battery Life (Earbuds)',
    'spec.battery_case': 'Battery Life (with Case)',
    'spec.pen': 'Pen',
    'spec.security': 'Security',
    'spec.os': 'Operating System',
    'spec.sound': 'Sound',
    'spec.fingerprint': 'Fingerprint Sensor',
    'spec.port': 'Port',
    'spec.sim': 'SIM',

    // Product Specs - Values
    'spec.value.retina_ltpo_oled_always_on': 'Retina LTPO OLED always-on',
    'spec.value.water_resistance_50m': 'Water resistant to 50 meters',
    'spec.value.sensors_s11': 'Blood Oxygen sensor, Electrical and Optical heart rate sensors, Body temperature sensor',
    'spec.value.features_s11': 'Crash Detection, Fall Detection, International Emergency SOS',
    'spec.value.battery_s11': 'Up to 18 hours (up to 36 hours in Low Power mode)',
    'spec.value.connectivity_s11': 'Wi-Fi, Bluetooth 5.3, GPS, Cellular',
    'spec.value.retina_ltpo_oled': 'Retina LTPO OLED',
    'spec.value.sensors_se11': 'Second-generation optical heart rate sensor, Accelerometer, Gyroscope, Altimeter',
    'spec.value.features_se': 'Crash Detection, Fall Detection, Emergency SOS',
    'spec.value.battery_18h': 'Up to 18 hours',
    'spec.value.connectivity_se': 'Wi-Fi, Bluetooth 5.3, GPS',
    'spec.value.sensors_se10': 'Second-generation optical heart rate sensor, Accelerometer, Gyroscope, Altimeter, Compass',
    'spec.value.features_se_sleep': 'Crash Detection, Fall Detection, Emergency SOS, Sleep tracking',
    'spec.value.active_noise_cancellation': 'Active Noise Cancellation',
    'spec.value.adaptive_transparency': 'Adaptive Transparency',
    'spec.value.personalized_spatial_audio': 'Personalized Spatial Audio with Dynamic Head Tracking',
    'spec.value.dual_beamforming_mics': 'Dual beamforming microphones',
    'spec.value.sensors_airpods_pro_2': 'Skin-detect sensor, Motion-detecting and speech-detecting accelerometer, Touch control',
    'spec.value.resistance_ipx4': 'Sweat and water resistant (IPX4)',
    'spec.value.battery_airpods_6h': 'Up to 6 hours of listening time on a single charge',
    'spec.value.battery_airpods_30h': 'Up to 30 hours of listening time',
    'spec.value.display_dynamic_amoled_6_8': 'Dynamic AMOLED 2X, 120Hz, HDR10+, 6.8 inches',
    'spec.value.camera_s25_ultra': '200MP (wide) + 50MP (periscope telephoto) + 10MP (telephoto) + 12MP (ultrawide)',
    'spec.value.battery_5000mah_45w': '5000 mAh, 45W fast charging',
    'spec.value.spen_ai': 'Built-in S Pen with AI support',
    'spec.value.display_dynamic_amoled_6_4': 'Dynamic AMOLED 2X, 120Hz, 6.4 inches',
    'spec.value.camera_s25_fe': '50MP (wide) + 8MP (telephoto) + 12MP (ultrawide)',
    'spec.value.battery_4500mah_25w': '4500 mAh, 25W fast charging',
    'spec.value.resistance_ip68': 'Water and dust resistant (IP68)',
    'spec.value.display_super_amoled_6_6': 'Super AMOLED, 120Hz, 6.6 inches',
    'spec.value.camera_a56': '50MP (wide) + 12MP (ultrawide) + 5MP (macro)',
    'spec.value.battery_5000mah_25w': '5000 mAh, 25W fast charging',
    'spec.value.display_super_amoled_6_6_120hz': 'Super AMOLED, 120Hz, 6.6 inches',
    'spec.value.camera_a36': '50MP (wide) + 8MP (ultrawide) + 5MP (macro)',
    'spec.value.resistance_ip67': 'Water and dust resistant (IP67)',
    'spec.value.display_super_amoled_6_5_120hz': 'Super AMOLED, 120Hz, 6.5 inches',
    'spec.value.camera_a26': '50MP (wide) OIS + 8MP (ultrawide) + 2MP (macro)',
    'spec.value.display_super_amoled_6_5_90hz': 'Super AMOLED, 90Hz, 6.5 inches',
    'spec.value.camera_a17': '50MP (wide) + 5MP (ultrawide) + 2MP (macro)',
    'spec.value.display_pls_lcd_6_7_90hz': 'PLS LCD, 90Hz, 6.7 inches',
    'spec.value.camera_a07': '50MP (wide) + 2MP (macro) + 2MP (depth sensor)',
    'spec.value.display_pls_lcd_6_7': 'PLS LCD, 6.7 inches',
    'spec.value.camera_a06': '50MP (wide) + 2MP (depth sensor)',
    'spec.value.display_tft_lcd_11_90hz': 'TFT LCD, 90Hz, 11.0 inches',
    'spec.value.sound_quad_dolby_atmos': 'Quad speakers with Dolby Atmos support',
    'spec.value.display_tft_lcd_8_7': 'TFT LCD, 8.7 inches',
    'spec.value.display_crystalres_amoled_6_36': 'CrystalRes AMOLED, 120Hz, Dolby Vision, 6.36 inches',
    'spec.value.camera_xiaomi_15t': '50MP Leica main camera + 50MP Leica telephoto + 50MP Leica ultrawide',
    'spec.value.battery_4610mah_90w': '4610 mAh, 90W HyperCharge',
    'spec.value.display_1_5k_amoled_6_67': '1.5K AMOLED, 120Hz, 6.67 inches',
    'spec.value.camera_redmi_note_14s': '200MP (wide) OIS + 8MP (ultrawide) + 2MP (macro)',
    'spec.value.battery_5100mah_67w': '5100 mAh, 67W fast charging',
    'spec.value.display_1_5k_crystalres_amoled_6_67': '1.5K CrystalRes AMOLED, 120Hz, 6.67 inches',
    'spec.value.camera_redmi_note_14_pro': '200MP (wide) OIS + 8MP (ultrawide) + 2MP (macro)',
    'spec.value.battery_5000mah_120w': '5000 mAh, 120W HyperCharge',
    'spec.value.display_amoled_6_67_120hz': 'AMOLED, 120Hz, 6.67 inches',
    'spec.value.camera_redmi_note_14': '108MP (wide) + 8MP (ultrawide) + 2MP (depth sensor)',
    'spec.value.battery_5000mah_33w': '5000 mAh, 33W fast charging',
    'spec.value.display_fhd_plus_amoled_6_79_90hz': 'FHD+ AMOLED, 90Hz AdaptiveSync, 6.79 inches',
    'spec.value.camera_redmi_15': '108MP (wide) + 2MP (macro)',
    'spec.value.battery_5030mah_33w': '5030 mAh, 33W fast charging',
    'spec.value.display_ips_lcd_6_74_90hz': 'IPS LCD, 90Hz, 6.74 inches',
    'spec.value.camera_redmi_15c': '50MP (wide) + 2MP (macro)',
    'spec.value.battery_5000mah_18w': '5000 mAh, 18W fast charging',
    'spec.value.display_ips_lcd_6_71_90hz': '6.71 inch, IPS LCD, 90Hz',
    'spec.value.display_flow_amoled_6_67_120hz': 'Flow AMOLED, 120Hz, 6.67 inches',
    'spec.value.camera_poco_m6': '64MP (wide) OIS + 8MP (ultrawide) + 2MP (macro)',
    'spec.value.battery_5000mah_67w': '5000 mAh, 67W fast charging',
    'spec.value.fingerprint_under_display': 'Under display',
    'spec.value.features_nokia_105': 'FM Radio (Wireless and Wired), Flashlight, Classic Games',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>(() => {
        const storedLanguage = typeof window !== 'undefined' ? localStorage.getItem('language') as Language : null;
        return storedLanguage || 'fa';
    });
    const direction: Direction = language === 'fa' ? 'rtl' : 'ltr';

    const toggleLanguage = () => {
        const newLanguage = language === 'fa' ? 'en' : 'fa';
        setLanguage(newLanguage);
        if (typeof window !== 'undefined') {
            localStorage.setItem('language', newLanguage);
        }
    };

    const t = (key: string): string => {
        const langTranslations = translations[language];
        if (langTranslations && key in langTranslations) {
            return langTranslations[key as keyof typeof langTranslations];
        }
        
        // Fallback to the other language if key not found
        const otherLanguage = language === 'fa' ? 'en' : 'fa';
        const fallbackTranslations = translations[otherLanguage];
        if (fallbackTranslations && key in fallbackTranslations) {
            return fallbackTranslations[key as keyof typeof fallbackTranslations];
        }

        return key; // Return the key itself if not found in any language
    };

    useEffect(() => {
        const storedLanguage = typeof window !== 'undefined' ? localStorage.getItem('language') as Language : null;
        if (storedLanguage && storedLanguage !== language) {
            setLanguage(storedLanguage);
        }
    }, []);

    useEffect(() => {
        document.documentElement.dir = direction;
        document.documentElement.lang = language;
        if (typeof window !== 'undefined') {
            localStorage.setItem('language', language);
        }
    }, [language, direction]);

    return (
        <LanguageContext.Provider value={{ language, direction, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
